# -*- coding: utf-8 -*-
"""Entrega 2 -  Álgebra Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lp5AsFOOWzHCwZf7GxxBXIUNwR-PnufW
"""

import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ============================================================
# 1. RECONSTRUÇÃO DA IMAGEM A PARTIR DO CSV (Entrega 1)
# ============================================================
df = pd.read_csv('matriz_arroz.csv', sep=';')

h = df['Linha'].max() + 1
w = df['Coluna'].max() + 1

img_reconst = np.zeros((h, w, 3), dtype=np.uint8)
for _, row in df.iterrows():
    img_reconst[int(row['Linha']), int(row['Coluna'])] = [row['R'], row['G'], row['B']]

img_small = img_reconst
cx, cy = w // 2, h // 2

print(f"Imagem reconstruída do CSV: {w}x{h} pixels")
print(f"Total de pixels: {len(df)}")

# ============================================================
# 2. ESCALONAMENTO (sx=1.5, sy=0.75)
# ============================================================
# S = [[1.5,  0  ],
#      [ 0 , 0.75]]
# det(S) = 1.125

S = np.array([[1.5, 0.0], [0.0, 0.75]])

M_scale = np.array([
    [1.5,  0.0,  cx * (1 - 1.5)],
    [0.0,  0.75, cy * (1 - 0.75)]
], dtype=np.float32)

img_scaled = cv2.warpAffine(img_small, M_scale, (w, h),
                             flags=cv2.INTER_LINEAR,
                             borderMode=cv2.BORDER_CONSTANT,
                             borderValue=(0, 0, 0))

print("\n=== ESCALONAMENTO ===")
print(f"det(S)  = {np.linalg.det(S):.4f}")
print(f"Autovalores de S: {np.linalg.eigvals(S)}")

# ============================================================
# 3. ROTAÇÃO (theta = 45°)
# ============================================================
# R = [[cos45, -sin45],
#      [sin45,  cos45]]
# det(R) = 1.0

R = np.array([
    [np.cos(np.radians(45)), -np.sin(np.radians(45))],
    [np.sin(np.radians(45)),  np.cos(np.radians(45))]
])

M_rot = cv2.getRotationMatrix2D((cx, cy), 45, scale=1.0)

img_rotated = cv2.warpAffine(img_small, M_rot, (w, h),
                              flags=cv2.INTER_LINEAR,
                              borderMode=cv2.BORDER_CONSTANT,
                              borderValue=(0, 0, 0))

print("\n=== ROTAÇÃO 45° ===")
print(f"det(R)  = {np.linalg.det(R):.4f}")
print(f"Autovalores de R: {np.linalg.eigvals(R)}")
print(f"R ortogonal (R @ R.T = I)? {np.allclose(R @ R.T, np.eye(2))}")

# ============================================================
# 4. CISALHAMENTO (k = 0.5)
# ============================================================
# Sh = [[1,  0.5],
#       [0,   1 ]]
# det(Sh) = 1.0

k = 0.5
Sh = np.array([[1.0, k], [0.0, 1.0]])

M_shear = np.array([
    [1.0,  k,  -k * cy],
    [0.0,  1.0,  0.0  ]
], dtype=np.float32)

img_sheared = cv2.warpAffine(img_small, M_shear, (w, h),
                              flags=cv2.INTER_LINEAR,
                              borderMode=cv2.BORDER_CONSTANT,
                              borderValue=(0, 0, 0))

print("\n=== CISALHAMENTO ===")
print(f"det(Sh) = {np.linalg.det(Sh):.4f}")
print(f"Autovalores de Sh: {np.linalg.eigvals(Sh)}")

# ============================================================
# 5. REFLEXÃO HORIZONTAL
# ============================================================
# Rf = [[-1, 0],
#       [ 0, 1]]
# det(Rf) = -1.0

Rf = np.array([[-1.0, 0.0], [0.0, 1.0]])

M_reflect = np.array([
    [-1.0,  0.0,  float(w - 1)],
    [ 0.0,  1.0,  0.0         ]
], dtype=np.float32)

img_reflected = cv2.warpAffine(img_small, M_reflect, (w, h),
                                flags=cv2.INTER_LINEAR,
                                borderMode=cv2.BORDER_CONSTANT,
                                borderValue=(0, 0, 0))

print("\n=== REFLEXÃO ===")
print(f"det(Rf) = {np.linalg.det(Rf):.4f}")
print(f"Autovalores de Rf: {np.linalg.eigvals(Rf)}")
print(f"Rf é sua própria inversa (Rf @ Rf = I)? {np.allclose(Rf @ Rf, np.eye(2))}")

# ============================================================
# 6. COLAPSO DIMENSIONAL — demonstração (det = 0)
# ============================================================
P = np.array([[1.0, 0.0], [0.0, 0.0]])

print("\n=== COLAPSO DIMENSIONAL ===")
print(f"det(P)  = {np.linalg.det(P):.1f}  → SINGULAR, não inversível")
print(f"dim(Núcleo) = 1, dim(Imagem) = 1, soma = 2  (Rank-Nullity)")

pixel = np.array([300.0, 150.0])
print(f"Pixel original:  {pixel}")
print(f"Após projeção P: {P @ pixel}  → y destruído, informação perdida")

# ============================================================
# 7. VERIFICAÇÃO GERAL
# ============================================================
print("\n=== RESUMO DAS PROPRIEDADES ===")
print(f"{'Transformação':<20} {'det':>8}   {'Autovalores'}")
print("-" * 65)
print(f"{'Escalonamento':<20} {np.linalg.det(S):>8.4f}   {np.linalg.eigvals(S)}")
print(f"{'Rotação 45°':<20} {np.linalg.det(R):>8.4f}   {np.linalg.eigvals(R)}")
print(f"{'Cisalhamento':<20} {np.linalg.det(Sh):>8.4f}   {np.linalg.eigvals(Sh)}")
print(f"{'Reflexão':<20} {np.linalg.det(Rf):>8.4f}   {np.linalg.eigvals(Rf)}")
print(f"{'Projeção (colapso)':<20} {np.linalg.det(P):>8.4f}   {np.linalg.eigvals(P)}")

# ============================================================
# 8. VISUALIZAÇÃO — títulos simples
# ============================================================
fig, axes = plt.subplots(1, 5, figsize=(25, 5))

imagens = [img_small, img_scaled, img_rotated, img_sheared, img_reflected]
titulos = [
    'Original',
    'Escalonamento',
    'Rotação 45°',
    'Cisalhamento',
    'Reflexão'
]

for ax, img_plot, titulo in zip(axes, imagens, titulos):
    ax.imshow(img_plot)
    ax.set_title(titulo, fontsize=12)
    ax.axis('off')

plt.suptitle('Transformações Lineares Aplicadas à Imagem do Arroz', fontsize=14)
plt.tight_layout()
plt.savefig('transformacoes_lineares.png', dpi=150, bbox_inches='tight')
plt.show()

