# -*- coding: utf-8 -*-
"""Entrega 2 - Sistemas Operacionais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7oLi0x33yBnu1RBX-sAR6JNocgcxh_t
"""

import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import time

print("Iniciando a carga de IA para o monitoramento...")

print("\n--- EXERCÍCIO 1: Criação e Tratamento de Dados (Pandas) ---")
# Gerando 100 mil linhas para forçar a CPU e a RAM da máquina
X, y = make_classification(n_samples=100000, n_features=20, random_state=42)
df = pd.DataFrame(X)
df['target'] = y
print(f"Dataset criado com sucesso! Tamanho: {df.shape[0]} linhas e {df.shape[1]} colunas.")
time.sleep(2) # Pequena pausa para você preparar o monitoramento

print("\n--- EXERCÍCIO 2: Treinamento do Modelo (Scikit-Learn) ---")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Criando um Random Forest pesado (200 árvores) para gerar o pico no gráfico
modelo = RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)
print("Treinando o Random Forest... (Verifique os gráficos de CPU agora!)")
modelo.fit(X_train, y_train)
print("Treinamento concluído!")

print("\n--- EXERCÍCIO 3: Previsão e Métricas de Avaliação ---")
previsoes = modelo.predict(X_test)
acuracia = accuracy_score(y_test, previsoes)
print(f"Acurácia do modelo: {acuracia * 100:.2f}%")

print("\nProcesso finalizado. O container continuará ativo por mais 40 segundos para você tirar os últimos prints.")
time.sleep(40)